---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
#   flake8
platforms:
  - name: bionic
    pre_build_image: true
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: focal
    pre_build_image: true
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
verifier:
  name: testinfra

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    # - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
