---
dependency:
  name: galaxy
driver:
  name: docker
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
#   flake8
platforms:
  - name: bionic
    pre_build_image: true
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: focal
    pre_build_image: true
    image: geerlingguy/docker-ubuntu2003-ansible:latest
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    command: /sbin/init
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    requirements-file: requirements.yml
